os: linux
dist: bionic
language: java
jdk: openjdk8

before_install:
  - curl -fsSL https://get.docker.com | sh
  - docker login --username $DOCKER_USERNAME --password $DOCKER_TOKEN
  - docker buildx version
  - docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
  - docker buildx create --use --name mybuilder

script: docker buildx build -t lamba92/wordnet-as-a-service --platform=linux/amd64,linux/arm64,linux/arm

deploy:
  provider: script
  script: docker buildx build -t lamba92/wordnet-as-a-service --platform=linux/amd64,linux/arm64,linux/arm --push
  skip_cleanup: true
  on:
    branch: master
    tags: true
